name: Simple CI pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run a simple command
        run: echo "this is my first pipeline"

      - name: step-1
        run: echo "this is my first step"

      - name: step-2
        run: echo "this is my second step"

      - name: pipeline break
        run: echo "pipeline fixed"

      - name: build docker image
        run: docker build -t devops .

      - name: login to ghcr
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: build a docker image
        run: docker build -t ghcr.io/${{ github.actor }}/devops:v1 .

      - name: docker push
        run: docker push ghcr.io/${{ github.actor }}/devops:v1
